# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

pool:
  name: 'Nortal agents pool'
  demands: docker
  vmImage: ubuntu-latest

variables:
  dockerRegistryServiceConnection: '0b6e4ff0-8e09-4840-bc90-67db95a5127a'
  imageRepository: 'mydocimage1'
  ImageName: 'javascriptapp'
  containerRegistry: 'nortalcicddemo.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/app/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: CI
  displayName: 'CI stage'
  jobs:
   - job: Build
     displayName: 'Build'
     steps:
      # Add all the tasks you need to build your project
   
     - task: Docker@2
       displayName: 'Build image'
       inputs:
         repository: '$(ImageName)'
         command: build
         Dockerfile: $(dockerfilePath)
         tags: $(Build.BuildId)
           
     - task: Docker@2
       displayName: 'Save image to TAR'
       inputs:
         repository: '$(ImageName)'
         command: save
         arguments: '--output $(build.artifactstagingdirectory)/$(ImageName).image.tar $(ImageName):$(Build.BuildId)'
         addPipelineData: false
   
     - task: PublishPipelineArtifact@1
       displayName: 'Publishing Image as Pipeline Artifact'
       inputs:
         path: $(build.artifactstagingdirectory)
         artifact: ContainerImage
