# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

pool:
  name: 'Nortal agents pool'
  demands: docker
  vmImage: ubuntu-latest

variables:
  dockerRegistryServiceConnection: '0b6e4ff0-8e09-4840-bc90-67db95a5127a'
  imageRepository: 'mydocimage1'
  imageName: 'mydocimage2'
  containerRegistry: 'nortalcicddemo.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/app/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Save image to TAR
      inputs:
        command: save
        Dockerfile: $(dockerfilePath)
        arguments: |
          --output $(build.artifactstagingdirectory)/$(imageName).image.tar $(imageName).$(tag)

